name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mod-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: "14" # Set the Node.js version

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
